import type { Types } from './types';

export const defaultA2UITheme: Types.Theme = {
  components: {
    AudioPlayer: { 'a2ui-audio-player': true },
    Button: { 'a2ui-button': true },
    Card: { 'a2ui-card': true },
    CheckBox: {
      container: { 'a2ui-checkbox': true },
      element: { 'a2ui-checkbox-element': true },
      label: { 'a2ui-checkbox-label': true },
    },
    Column: { 'a2ui-column': true },
    DateTimeInput: {
      container: { 'a2ui-date-time-input': true },
      label: { 'a2ui-date-time-input-label': true },
      element: { 'a2ui-date-time-input-element': true },
    },
    Divider: { 'a2ui-divider': true },
    Icon: { 'a2ui-icon': true },
    Image: {
      all: { 'a2ui-image': true },
      icon: { 'a2ui-image-icon': true },
      avatar: { 'a2ui-image-avatar': true },
      smallFeature: { 'a2ui-image-small-feature': true },
      mediumFeature: { 'a2ui-image-medium-feature': true },
      largeFeature: { 'a2ui-image-large-feature': true },
      header: { 'a2ui-image-header': true },
    },
    List: { 'a2ui-list': true },
    Modal: {
      backdrop: { 'a2ui-modal-backdrop': true },
      element: { 'a2ui-modal-element': true },
    },
    MultipleChoice: {
      container: { 'a2ui-multiple-choice': true },
      label: { 'a2ui-multiple-choice-label': true },
      element: { 'a2ui-multiple-choice-element': true },
    },
    Row: { 'a2ui-row': true },
    Slider: {
      container: { 'a2ui-slider': true },
      label: { 'a2ui-slider-label': true },
      element: { 'a2ui-slider-element': true },
    },
    Tabs: {
      container: { 'a2ui-tabs': true },
      element: { 'a2ui-tabs-element': true },
      controls: {
        all: { 'a2ui-tab': true },
        selected: { 'a2ui-tab-selected': true },
      },
    },
    Text: {
      all: { 'a2ui-text': true },
      h1: { 'a2ui-text-h1': true },
      h2: { 'a2ui-text-h2': true },
      h3: { 'a2ui-text-h3': true },
      h4: { 'a2ui-text-h4': true },
      h5: { 'a2ui-text-h5': true },
      caption: { 'a2ui-text-caption': true },
      body: { 'a2ui-text-body': true },
    },
    TextField: {
      container: { 'a2ui-text-field': true },
      label: { 'a2ui-text-field-label': true },
      element: { 'a2ui-text-field-element': true },
    },
    Video: { 'a2ui-video': true },
  },
  elements: {
    a: {},
    audio: {},
    body: {},
    button: {},
    h1: {},
    h2: {},
    h3: {},
    h4: {},
    h5: {},
    iframe: {},
    input: {},
    p: {},
    pre: {},
    textarea: {},
    video: {},
  },
  markdown: {
    p: [],
    h1: [],
    h2: [],
    h3: [],
    h4: [],
    h5: [],
    ul: [],
    ol: [],
    li: [],
    a: [],
    strong: [],
    em: [],
  },
};
